# Generated by Django 2.2.2 on 2019-06-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='profile/', verbose_name='Profile Pic'),
        ),
    ]
