# Generated by Django 2.2.2 on 2019-06-13 03:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190610_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 3, 55, 26, 282607, tzinfo=utc)),
        ),
    ]
