# Generated by Django 2.2.2 on 2019-06-17 01:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190613_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 1, 58, 13, 822012, tzinfo=utc)),
        ),
    ]
